In [1]:
# Importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
# Importing dataset
dataset = pd.read_csv('/home/gxuvimr/Documents/Machine Learning A-Z Template Folder/Part 1 - Data Preprocessing/Data.csv')

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

# Taking care of missing data (numerical data)
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [3]:
# Transformation of categorical data
from sklearn.compose import ColumnTransformer

# For giving weights to each label
from sklearn.preprocessing import LabelEncoder
label_encoder_y = LabelEncoder()
y = label_encoder_y.fit_transform(y)

# For giving equal value to all, using dummy variables
# Splitting into n variables
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],
    remainder='passthrough'
    )
X = ct.fit_transform(X)

for i in range(len(X)):
    print(X[i], y[i])
print()

[1.0 0.0 0.0 44.0 72000.0] 0
[0.0 0.0 1.0 27.0 48000.0] 1
[0.0 1.0 0.0 30.0 54000.0] 0
[0.0 0.0 1.0 38.0 61000.0] 0
[0.0 1.0 0.0 40.0 63777.77777777778] 1
[1.0 0.0 0.0 35.0 58000.0] 1
[0.0 0.0 1.0 38.77777777777778 52000.0] 0
[1.0 0.0 0.0 48.0 79000.0] 1
[0.0 1.0 0.0 50.0 83000.0] 0
[1.0 0.0 0.0 37.0 67000.0] 1



In [4]:
# Splitting training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)
print(X_train, X_test, y_train, y_test)


[[1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]] [[0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 50.0 83000.0]] [1 0 1 1 1 0 0] [1 0 0]


In [5]:
# TODO: Also some feature Scaling
# TODO: A better way of one-hot encoding